config/routes.rb
Rails.application.routes.draw do
  get 'sso/authenticate'

  # See how all your routes lay out with "rake routes".

  root                     to: 'communities#index'
  get 'new'                 => 'special_pages#new_to_cornerstone'
  get 'times-and-locations' => 'special_pages#times_and_locations'
  get 'invest-in-community' => 'special_pages#invest_in_cornerstone'

  # Search
  get  'search' => 'search#index'
  get  'search/preload'     => 'search#preload'
  resources :search_sessions, only:[:create,:update,:show]

  resources :media do
  end

  resources :pages, only:[:show]
  resources :posts, only:[:index, :show]

  # Library
  resources :studies, only: [:index, :show ], path: 'library' do
    resources :lessons, only: [:index, :show ] do
      resources :questions, only: [:index, :show, :new, :create], shallow: true do
        post :block, :star, :on => :member
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true do
          post :block, :star, :on => :member
        end
      end
    end
  end

  # Ministry
  get '/:id'  => 'communities#show', constraints: {id: /men|women|rendezvous|teens|kids|outreach/}

  # # Questions
  # resources :questions do
  #   resources :answers
  # end

  # Groups
  resources :groups do
    resources :meetings do
      resources :questions, only: [:index, :new, :create]
      # NOTE: :block, :star, :show, :answers
      # already part of the previous shallow routes
    end
  end

  devise_for :users, :skip => [:sessions], :controllers => { invitations: 'devise_override/invitations', registrations:'devise_override/registrations' }
  as :user do
    # get     'join'    => 'devise_override/registrations#new', :as => :new_registrations
    get     'invite'  => 'devise_override/invitations#new',  :as => :new_invitation
    get     'login'   => 'devise/sessions#new',           :as => :new_user_session
    post    'login'   => 'devise/sessions#create',        :as => :user_session
    delete  'logout'  => 'devise/sessions#destroy',       :as => :destroy_user_session
    get     'logout'  => 'devise/sessions#destroy' #convenience
  end

  get 'admin' => 'admin/posts#index'
  namespace :admin do
    resources :faq_answers

    resources :ministries, except: :show
    resources :posts do
      collection do
        get 'link_preview'
        delete 'video_complete_upload'
      end
    end

    resources :comm_arts_requests, only: [:index, :create] do
      member do
        get 'toggle_archive'
      end
    end

    resources :uploaded_files, only: [:index, :create, :destroy]
    patch 'uploaded_files' => 'uploaded_files#create'

    get 'editable_posts' => 'approval_requests#editable_posts'
    resources :approval_requests, only: [:show, :update] do
      member do
        get 'update_status_from_link'
      end
    end

    resources :studies, :lessons

    namespace :content do
      resources :pages
    end

  end

  namespace :api do
    get 'groups'
    get 'current_lesson'
    get 'group'
    post 'login'
    get 'login_and_visit'
  end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable


  require 'mixins/http_authentication'
  mount RESQUE_DASHBOARD, at: "/queue"

  authenticate :user, lambda{|user| user.admin? } do
    mount Searchjoy::Engine, at: "admin/searchjoy"
  end

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id                      :integer          not null, primary key
#  state                   :string(50)       not null
#  name                    :string           not null
#  description             :text             not null
#  is_public               :boolean          default("true")
#  meets_every_days        :integer          default("7")
#  meetings_count          :integer          default("0")
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  type                    :text             not null
#  study_id                :integer
#  approved_at             :datetime
#  poster_img_file_name    :string
#  poster_img_content_type :string
#  poster_img_file_size    :integer
#  poster_img_updated_at   :datetime
#  poster_img_fingerprint  :string
#  poster_img_processing   :boolean
#  study_group_data        :jsonb            default("{}"), not null
#  book_group_data         :jsonb            default("{}"), not null
#  affinity_group_data     :jsonb            default("{}"), not null
#  public_id               :string(20)
#
# Indexes
#
#  index_groups_on_public_id            (public_id)
#  index_groups_on_state_and_is_public  (state,is_public)
#  index_groups_on_study_id             (study_id)
#  index_groups_on_type_and_id          (type,id)
#

class Group < ActiveRecord::Base
  include AttachableFile
  include Uuidable

  # ---------------------------------------------------------------------------------
  # Attributes
  # ---------------------------------------------------------------------------------
  # attr_accessible :description, :name, :is_public, :state, :meets_every_days, :poster_img, :poster_img_remote_url
  # attr_accessible :members, :members_attributes,  as: 'leader'

  has_public_id :public_id, prefix:'GRP', length:20

  has_attachable_file :poster_img,
                      :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"],
                      :processors => [:thumbnail, :paperclip_optimizer],
                      paperclip_optimizer: { jhead:true, jpegrecompress:true, jpegtran:true },
                      :styles => {
                        large:        { geometry: "1500x1500>", format: 'jpg', convert_options: "-strip" },
                        medium:       { geometry: "500x500>",   format: 'jpg', convert_options: "-strip" },
                        small:        { geometry: "200x200>",   format: 'jpg', convert_options: "-strip" },
                        large_thumb:  { geometry: "120x120#",   format: 'jpg', convert_options: "-strip" },
                        thumb:        { geometry: "100x100#",   format: 'jpg', convert_options: "-strip" }
                      }

  process_in_background :poster_img

  # ---------------------------------------------------------------------------------
  # Associations
  # ---------------------------------------------------------------------------------
  belongs_to :study
  has_one  :current_meeting,    -> { where state: 'current'},  :class_name => "Meeting", foreign_key: 'group_id'
  has_many :meetings,           :dependent => :destroy,        :class_name => "Meeting", foreign_key: 'group_id'
  has_many :questions,          as: 'source'
  has_many :lessons,                      through: :study
  has_many :lessons_through_meetings,     through: :meetings, source: :lesson

  has_many :members,            :through => :group_memberships
  # has_many :leaders,            :through => :group_memberships, source: 'member', conditions: 'group_memberships.role_level > 1'
  has_many :group_memberships,  :dependent => :destroy, inverse_of: :group
  accepts_nested_attributes_for :group_memberships,
                                allow_destroy: true,
                                reject_if: lambda { !(attributes[:members_attributes].try(:[], :user_id)) }

  def leaders; members.where('group_memberships.role_level > 1') ;end

  # ---------------------------------------------------------------------------------
  # Validations
  # ---------------------------------------------------------------------------------
  validates_presence_of :name, :description, :state



  # ---------------------------------------------------------------------------------
  # StateMachine
  # ---------------------------------------------------------------------------------
  include AASM
  aasm column:'state' do #no_direct_assignment:true
    state :is_open, initial: true
    state :is_closed
    state :is_finished
  end


  # ---------------------------------------------------------------------------------
  # Scopes
  # ---------------------------------------------------------------------------------
  # scope :for_user, -> {|user| where(user)}
  scope :is_public,           -> {where(is_public: true)}
  scope :publicly_searchable, -> {is_public.is_open}



  # ---------------------------------------------------------------------------------
  # Callbacks
  # ---------------------------------------------------------------------------------
  # after_save :create_first_meeting


  # ---------------------------------------------------------------------------------
  # Methods
  # ---------------------------------------------------------------------------------


end

app/models/groups/affinity_group.rb
# == Schema Information
#
# Table name: groups
#
#  id                      :integer          not null, primary key
#  state                   :string(50)       not null
#  name                    :string           not null
#  description             :text             not null
#  is_public               :boolean          default("true")
#  meets_every_days        :integer          default("7")
#  meetings_count          :integer          default("0")
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  type                    :text             not null
#  study_id                :integer
#  approved_at             :datetime
#  poster_img_file_name    :string
#  poster_img_content_type :string
#  poster_img_file_size    :integer
#  poster_img_updated_at   :datetime
#  poster_img_fingerprint  :string
#  poster_img_processing   :boolean
#  study_group_data        :jsonb            default("{}"), not null
#  book_group_data         :jsonb            default("{}"), not null
#  affinity_group_data     :jsonb            default("{}"), not null
#  public_id               :string(20)
#
# Indexes
#
#  index_groups_on_public_id            (public_id)
#  index_groups_on_state_and_is_public  (state,is_public)
#  index_groups_on_study_id             (study_id)
#  index_groups_on_type_and_id          (type,id)
#

class Groups::AffinityGroup < Group
  delegate_attrs_to_jsonb to: :affinity_group_data
end

app/models/groups/book_group.rb
# == Schema Information
#
# Table name: groups
#
#  id                      :integer          not null, primary key
#  state                   :string(50)       not null
#  name                    :string           not null
#  description             :text             not null
#  is_public               :boolean          default("true")
#  meets_every_days        :integer          default("7")
#  meetings_count          :integer          default("0")
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  type                    :text             not null
#  study_id                :integer
#  approved_at             :datetime
#  poster_img_file_name    :string
#  poster_img_content_type :string
#  poster_img_file_size    :integer
#  poster_img_updated_at   :datetime
#  poster_img_fingerprint  :string
#  poster_img_processing   :boolean
#  study_group_data        :jsonb            default("{}"), not null
#  book_group_data         :jsonb            default("{}"), not null
#  affinity_group_data     :jsonb            default("{}"), not null
#  public_id               :string(20)
#
# Indexes
#
#  index_groups_on_public_id            (public_id)
#  index_groups_on_state_and_is_public  (state,is_public)
#  index_groups_on_study_id             (study_id)
#  index_groups_on_type_and_id          (type,id)
#

class Groups::BookGroup < Group
  delegate_attrs_to_jsonb :purchase_link,
    to: :book_group_data
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!,  except:[:index, :show]
  before_filter :safe_select_group,   only: [:show, :edit, :update, :destroy]
  before_filter :safe_select_groups,  only: [:index]

  # GET /groups
  # GET /groups.json
  def index
    if user_signed_in?
      @groups = current_user.groups.includes(:meetings, :lessons_through_meetings)
      @open_groups = @groups.select { |group| group.is_open? }
      @finished_groups = @groups.select { |group| group.is_finished? }
      @user_lesson_states = current_user.user_lesson_states
      .where(['lesson_id IN(?)', @groups.map {|group| group.lessons_through_meetings.map(&:id) }.flatten.uniq])

      template= 'index'
    else
      @groups = Group.includes(:meetings).publicly_searchable.all
      template= 'public_index'
    end

    respond_to do |format|
      format.html { render template: "groups/#{template}" }
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    if user_signed_in?
      @membership.touch #last_attended_at
      template= 'show'
    else
      @group = Group.publicly_searchable.find( params[:id] )
      template= 'public_show'
    end
    respond_to do |format|
      format.html { render template: "groups/#{template}" }
      format.json { render json: @group }
    end

  rescue ActiveRecord::RecordNotFound
    redirect_to user_signed_in? ? groups_url : new_user_session_url
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group ||= group_params[:type].constantize.new(group_params)
    @group.errors.add(:type, 'Not a valid group') unless @group.is_a?(Group)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group.becomes(Group), notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group.becomes(Group) }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update

    respond_to do |format|
      if @group.update_attributes(group_params)
        format.html { redirect_to @group.becomes(Group), notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

private

  def group_params
    raise ArgumentError unless ['Groups::StudyGroup'].include? params[:group][:type]
    @group_params ||= params.require(:group).permit(
      :description, :name, :is_public, :state, :meets_every_days, :poster_img, :poster_img_remote_url, :type,
      :study_id
    )
  end

  # scopes SELECT to current user
  def safe_select_groups
    return unless user_signed_in?
    @groups = current_user.groups
  end

  # scopes SELECT to current user
  def safe_select_group
    return unless user_signed_in? && params[:id]
    @membership = current_user.membership_in(params[:id])
    @group      = @membership.group
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def current_meeting_from(group)
    group.meetings.detect { |m| m.date_of > Time.now }
  end

  def current_meeting_position(meeting, current_meeting)
    return "finished" if current_meeting.blank?
    if meeting.position < current_meeting.position
      "past"
    elsif meeting.position == current_meeting.position
      "current"
    elsif meeting.position > current_meeting.position
      "future"
    end
  end

  def percent_completed(user_lesson_state, lesson)
    if lesson.duration.present?
      user_lesson_state.media_progress.to_f/lesson.duration.to_f * 100.0
    else
      0.0
    end
  end

end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    #error_explanation.alert.alert-danger.alert-dismissible{role:'alert'}
      %button.close.fade.in{data:{dismiss:'alert'}}
        %span{'aria-hidden'=>true} &times;
        %span.sr-only Close
      %h2= "#{pluralize(@group.errors.count, "error")} prevented this post from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :is_public, name: 'Public?'
    %br/
    = f.number_field :is_public
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/groups/_group_row.html.haml
- groups.each do |group|
  .row
    .col-sm-6
      = link_to(image_tag(group.poster_img.url), group_path(group))
    .col-sm-6
      .title.row
        .lead.text-right
          = truncate(group.name, length: 35)
      .name.row.small
        Cornerstone Church?
      .row.new-activity
        %a
          New Activity
          %span.badge 7
  %a.row.step-progress{"data-toggle" => "collapse", "href" => "#collapseGroup#{group.id}"}
    .col-xs-9
      - group.meetings.each do |meeting|
        - current_meeting_position = current_meeting_position(meeting, current_meeting_from(group))
        .step-progress-step{class:["#{current_meeting_position}", "col-xs-#{12/group.meetings.length}"].join(' ')}
          .progress
            .progress-bar
          .step-progress-dot
            %i.glyphicon
    .expand.col-xs-3
      %button.btn.btn-default See All
  .collapse{id: "collapseGroup#{group.id}"}
    .row
      - group.meetings.each_with_index do |meeting, index|
        - numbered_list = index + 1
        .row
          - lesson = meeting.lesson
          .col-xs-1
            - current_meeting_position = current_meeting_position(meeting, current_meeting_from(group))
            .group-progress{class: "#{current_meeting_position}"}
          .col-xs-6
            = "#{numbered_list}. #{lesson.title}"
          .col-xs-5
            - user_lesson_state = @user_lesson_states.find {|state| state.lesson_id == lesson.id}
            .progress
              .progress-bar.progress-bar-striped{style: "width: #{percent_completed(user_lesson_state, lesson)}%"}
                = "#{percent_completed(user_lesson_state, lesson).round(1)}%"

app/views/groups/_sidebar.html.haml
= content_for :sidebar do
  .span3
    .well.sidebar-nav
      %ul.nav.nav-list
        %li.nav-header Sidebar
        %li= link_to "Link1", "/path1"
        %li= link_to "Link2", "/path2"
        %li= link_to "Link3", "/path3"
    / /.well
  / /span

app/views/groups/edit.html.haml
= (render partial: 'sidebar')
%h1 Editing group
= render 'form'
= link_to 'Show', @group
|
\#{link_to 'Back', groups_path}

app/views/groups/index.html.haml
- content_for :page_specific_js_initializers do
  = javascript_include_tag "groups/"

= (render partial: 'sidebar')

.container
  .col-md-7.display
    %h3.group-title My Groups

    .member-groups
      =render partial: "group_row", locals: { groups: @open_groups }
  .col-md-5
    %h3.group-title Active Questions

.container
  .col-md-7.display
    %h3.group-title Archived Groups

    .member-groups
      =render partial: "group_row", locals: { groups: @finished_groups }

app/views/groups/new.html.haml
= (render partial: 'sidebar')
%h1 New group
= render 'form'
= link_to 'Back', groups_path

app/views/groups/public_index.html.haml
= (render partial: 'sidebar')

- content_for(:page_specific_js) do
  = javascript_include_tag 'groups/public_index'

#groups-public
  .row
    .col-xs-6
      .well
        .form-inline
          .form-group
            = text_field_tag('email', nil, id: 'email_field', class: 'form-control', placeholder: 'Enter email...')
            = label_tag(:sign_up, 'Sign Up', id: 'join_button', class: 'btn btn-default')
    .col-xs-6
      .well{ id: 'login_button' }
        = label_tag(:login, 'Log In To Your Groups', class: 'btn')

%h3 Study groups
#groups-study-list
  - @groups.each do |group|
    = link_to(image_tag(group.poster_img.url), group_path(group))

app/views/groups/public_show.html.haml
= (render partial: 'sidebar')
%h2 Public
%p#notice= notice
%p
  %b Name:
  = @group.name
%p
  %b Desription:
  = @group.description
%p
  %b Study:
  = @group.study_id
= link_to 'Edit', edit_group_path(@group)
|
\#{link_to 'Back', groups_path}

app/views/groups/show.html.haml
%small
= (render partial: 'sidebar')
%p#notice= notice
%p
  %b Name:
  = @group.name
%p
  %b Desription:
  = @group.description
  %small
= link_to 'Edit', edit_group_path(@group)
|
\#{link_to 'Back', groups_path}