config/routes.rb
Rails.application.routes.draw do
  get 'sso/authenticate'

  # See how all your routes lay out with "rake routes".

  root                     to: 'communities#index'
  get 'new'                 => 'special_pages#new_to_cornerstone'
  get 'times-and-locations' => 'special_pages#times_and_locations'
  get 'invest-in-community' => 'special_pages#invest_in_cornerstone'

  # Search
  get  'search' => 'search#index'
  get  'search/preload'     => 'search#preload'
  resources :search_sessions, only:[:create,:update,:show]

  resources :media do
  end

  resources :pages, only:[:show]
  resources :posts, only:[:index, :show]

  # Library
  resources :studies, only: [:index, :show ], path: 'library' do
    resources :lessons, only: [:index, :show ] do
      resources :questions, only: [:index, :show, :new, :create], shallow: true do
        post :block, :star, :on => :member
        resources :answers, only: [:index, :show, :create, :update, :destroy], shallow: true do
          post :block, :star, :on => :member
        end
      end
    end
  end

  # Ministry
  get '/:id'  => 'communities#show', constraints: {id: /men|women|rendezvous|teens|kids|outreach/}

  # # Questions
  # resources :questions do
  #   resources :answers
  # end

  # Groups
  resources :groups do
    resources :meetings do
      resources :questions, only: [:index, :new, :create]
      # NOTE: :block, :star, :show, :answers
      # already part of the previous shallow routes
    end
  end

  devise_for :users, :skip => [:sessions], :controllers => { invitations: 'devise_override/invitations', registrations:'devise_override/registrations' }
  as :user do
    # get     'join'    => 'devise_override/registrations#new', :as => :new_registrations
    get     'invite'  => 'devise_override/invitations#new',  :as => :new_invitation
    get     'login'   => 'devise/sessions#new',           :as => :new_user_session
    post    'login'   => 'devise/sessions#create',        :as => :user_session
    delete  'logout'  => 'devise/sessions#destroy',       :as => :destroy_user_session
    get     'logout'  => 'devise/sessions#destroy' #convenience
  end

  get 'admin' => 'admin/posts#index'
  namespace :admin do
    resources :faq_answers

    resources :ministries, except: :show
    resources :posts do
      collection do
        get 'link_preview'
        delete 'video_complete_upload'
      end
    end

    resources :comm_arts_requests, only: [:index, :create] do
      member do
        get 'toggle_archive'
      end
    end

    resources :uploaded_files, only: [:index, :create, :destroy]
    patch 'uploaded_files' => 'uploaded_files#create'

    get 'editable_posts' => 'approval_requests#editable_posts'
    resources :approval_requests, only: [:show, :update] do
      member do
        get 'update_status_from_link'
      end
    end

    resources :studies, :lessons

    namespace :content do
      resources :pages
    end

  end

  namespace :api do
    get 'groups'
    get 'current_lesson'
    get 'group'
    post 'login'
    get 'login_and_visit'
  end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable


  require 'mixins/http_authentication'
  mount RESQUE_DASHBOARD, at: "/queue"

  authenticate :user, lambda{|user| user.admin? } do
    mount Searchjoy::Engine, at: "admin/searchjoy"
  end

end

app/models/media_hub/study.rb
# == Schema Information
#
# Table name: studies
#
#  id                      :integer          not null, primary key
#  slug                    :string           not null
#  channel_id              :integer          not null
#  podcast_id              :integer
#  position                :integer          not null
#  title                   :string           not null
#  description             :text
#  keywords                :text             default("{}"), is an Array
#  ref_link                :string
#  poster_img_file_name    :string
#  poster_img_content_type :string
#  poster_img_file_size    :integer
#  poster_img_updated_at   :datetime
#  poster_img_original_url :string
#  poster_img_fingerprint  :string
#  poster_img_processing   :boolean
#  lessons_count           :integer          default("0")
#  last_published_at       :datetime
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_studies_on_last_published_at                 (last_published_at)
#  index_studies_on_podcast_id_and_last_published_at  (podcast_id,last_published_at)
#  index_studies_on_slug                              (slug) UNIQUE
#

class Study < ActiveRecord::Base
  include Sortable
  include Sluggable
  include Sanitizable
  include AttachableFile
  # include Study::Search

  TEACHING_CHANNELS = %w{ messages studies resources mens-retreat coffeetalk }
  MUSIC_CHANNELS    = %w{ music }
  ARTS_CHANNELS     = %w{ dramavideo }

  # ---------------------------------------------------------------------------------
  # Attributes
  # ---------------------------------------------------------------------------------
  attr_accessible :title, :description, :ref_link,  :poster_img, :poster_img_remote_url, :podcast, :podcast_id
  attr_accessible *column_names, *reflections.keys, :poster_img, :poster_img_remote_url, :podcast, :podcast_id, as: 'sudo'
  delegate :church_name, to: :podcast

  acts_as_listable scope: :channel

  slug_candidates :title, [:title, :year], [:title, :month, :year], [:title, :month, :date, :year]

  has_attachable_file :poster_img,
                      :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"],
                      :processors => [:thumbnail, :paperclip_optimizer],
                      paperclip_optimizer: { jhead:true, jpegrecompress:true, jpegtran:true },
                      :styles => {
                        large:        { geometry: "1500x1500>", format: 'jpg', convert_options: "-strip" },
                        medium:       { geometry: "500x500>",   format: 'jpg', convert_options: "-strip" },
                        small:        { geometry: "200x200>",   format: 'jpg', convert_options: "-strip" },
                        large_thumb:  { geometry: "120x120#",   format: 'jpg', convert_options: "-strip" },
                        thumb:        { geometry: "100x100#",   format: 'jpg', convert_options: "-strip" }
                      }

  process_in_background :poster_img


  # ---------------------------------------------------------------------------------
  # Associations
  # ---------------------------------------------------------------------------------
  belongs_to :channel
  belongs_to :podcast, :inverse_of => :studies
  has_one :church,     :through => :podcast, :inverse_of => :studies
  has_many :lessons, -> {order 'lessons.position ASC'}, {:dependent => :destroy, class_name:'Lesson'}# do
  #   def number(n, strict=false)
  #     raise ActiveRecord::RecordNotFound if strict && (n > self.length) #lessons_count
  #     where(position:n).first
  #   end
  # end
  has_many :groups


  # ---------------------------------------------------------------------------------
  # Validations
  # ---------------------------------------------------------------------------------
  validates_presence_of :slug, :title, :channel
  # validates_uniqueness_of :title, :scope => :podcast_id


  # ---------------------------------------------------------------------------------
  # Callbacks
  # ---------------------------------------------------------------------------------
  before_validation :add_default_values


  # ---------------------------------------------------------------------------------
  # Scopes
  # ---------------------------------------------------------------------------------
  scope :teaching, -> { where(channel_id: Channel.where(slug:TEACHING_CHANNELS).pluck(:id)) }
  scope :music,    -> { where(channel_id: Channel.where(slug:MUSIC_CHANNELS).pluck(:id)) }
  scope :arts,     -> { where(channel_id: Channel.where(slug:ARTS_CHANNELS).pluck(:id)) }
  scope :w_lessons, -> {includes(:lessons)}


  # ---------------------------------------------------------------------------------
  # Methods
  # ---------------------------------------------------------------------------------
  class << self
    def new_from_podcast_channel(podcast_channel, attribute_overrides={})
      new({
        title:                  podcast_channel.title,
        description:            podcast_channel.description,
        ref_link:               podcast_channel.homepage,
        poster_img_remote_url:  podcast_channel.poster_img,
        last_published_at:      podcast_channel.last_updated,
      }.merge(attribute_overrides), as: 'sudo')
    end
  end


  # Answers "Is this lesson part of this study?"
  def include?(lesson)
    raise ArgumentError.new('Study#include? requires a @lesson') unless lesson.is_a? Lesson
    lessons.include? lesson
  end

  # Determins if a lesson SHOULD part of this study
  # => false if lessons.empty?
  def should_include?(lesson)
    raise ArgumentError.new('Study#include? requires a @lesson') unless lesson.is_a? Lesson
    !!(lessons.last.try :belongs_with?, lesson)
  end

  # Single lesson study
  def stand_alone?
    lessons.size == 1 #lessons_count
  end

  # Replace original http://apidock.com/rails/ActiveRecord/Persistence/touch
  def touch(*names)
    self.lessons_count     = lessons.length
    self.last_published_at = lessons.map(&:published_at).max
    self.updated_at        = Time.now
    self.save!
  end

  def organization
    # future association
  end

  def tags
    # future association
  end

  def authors
    if lessons.loaded?
      lessons.map(&:author)
    else
      lessons.pluck(:author)
    end.uniq.join(', ')
  end

  private #--------------------------------------------------------------------------------

  def add_default_values
    self.channel_id || self.channel ||= Channel.first
  end
end

# Support the namespacing convention for rake tasks etc.
MediaHub::Study = Study

app/controllers/admin/studies_controller.rb
class Admin::StudiesController < Admin::BaseController

  # GET /admin/studies?search=keyword
  # GET /admin/studies.json
  def index
    @studies = (
      if params[:search]
        Study.search do
          fulltext params[:search]
        end

      else # Not searching
        Study.all
      end
    )
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studies }
    end
  end

  # GET /admin/studies/name-of-study
  # GET /admin/studies/name-of-study.json
  def show
    @study = Study.friendly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @study }
    end
  end

  # GET /admin/studies/new
  # GET /admin/studies/new.json
  def new
    @study = Study.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @study }
    end
  end

  # GET /admin/studies/1/edit
  def edit
    @study = Study.friendly.find(params[:id])
  end

  # POST /admin/studies
  # POST /admin/studies.json
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        format.html { redirect_to admin_study_url(@study), notice: 'Study was successfully created.' }
        format.json { render json: @study, status: :created, location: @study }
      else
        format.html { render action: "new" }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/studies/name-of-study
  # PUT /admin/studies/name-of-study.json
  def update
    @study = Study.friendly.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        format.html { redirect_to admin_study_url(@study), notice: 'Study was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/studies/name-of-study
  # DELETE /admin/studies/name-of-study.json
  def destroy
    @study = Study.friendly.find(params[:id])
    @study.destroy

    respond_to do |format|
      format.html { redirect_to admin_studies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  # caches_page :show

  # GET /library?search=keyword
  # GET /library.json
  def index
    # @channels = Channel.all
    @studies = (
      if params[:search]
        Study.search do
          fulltext params[:search]
        end

      else # Not searching
        Study.where('lessons_count > 0')
        .where('poster_img_file_name is NOT NULL')
        .includes(:lessons)
        .limit(20)
        .all
      end
    )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studies }
    end
  end

  # GET /library/name-of-study
  # GET /library/name-of-study.json
  def show
    @study      = find_or_redirect_to_study || return #redirecting
    @lessons    = @study.lessons

    # Users last watched or... for now
    @lesson = @lessons.first

    respond_to do |format|
      format.html { redirect_to study_lesson_url(@study, @lesson) }
      format.json { render json: @study }
    end
  end

private

  # Return @study OR follow old friendly_id
  # Usage: @study = find_or_redirect_to_study || return #redirecting
  def find_or_redirect_to_study
    study = Study.w_lessons.friendly.find(params[:id])
    unless request.path == study_path(study)
      redirect_to( study_url(study), status: :moved_permanently ) && (return false)
    end
    return study
  end

end

app/helpers/admin/studies_helper.rb
module Admin::StudiesHelper
end

app/helpers/studies_helper.rb
module StudiesHelper

  # Creates a visually 'random' grid (well hash of column widths)
  # #=> [ # Study is the key
  #       {<#Study>:4, <#Study>:4, <#Study>:4},
  #       {<#Study>:3, <#Study>:3, <#Study>:3, <#Study>:3},
  #     ]
  def grid_layout_for(collection, options={})
    GridLayout.new(collection, options).as_json
  end

  class GridLayout
    def initialize(collection, options={})
      @rows = []
      @collection = @pristine_collection = collection.to_a
      @options = { rows_since_possible_repeat: 3, tidy_ending:true }.merge(options)
      @layout_column_counts = [
        [3,3,3,3],
        [4,4,4],
        [3,4,5],
        [3,3,6]
      ].inject([]) {|array,grid_width| (array | grid_width.permutation.to_a.uniq)}.freeze
    end

    def as_json
      collection_to_rows.inject([]) do |array, row_array|
        array << row_array.inject({}){|hash, col| hash[ @collection.shift]=col; hash}
      end
    end

  private

    def collection_to_rows
      while remaining_collection_items > 0
        @rows << find_uniq_layout
      end
      @rows
    end

    def find_uniq_layout
      return tidy_ending      if @options[:tidy_ending] && tidy_ending
      return random_grid_row  if trailing_rows.empty?

      maybe = random_grid_row
      maybe = find_uniq_layout if @trailing_rows_cache.include?(maybe)
      maybe = find_uniq_layout if @trailing_rows_cache.last[0] == maybe[0]
      maybe = find_uniq_layout if @trailing_rows_cache.last[-1] == maybe[-1]
      yes   = maybe
    end

    # Establishes a 'no repeat' zone
    def trailing_rows
      floor = [@rows.count - @options[:rows_since_possible_repeat], 0].max
      @trailing_rows_cache = Array.wrap( @rows[floor...@rows.count] )
    end

    def tidy_ending
      case remaining_collection_items
        when 1 then [12]
        when 2 then [7,5]
        when 4 then [3,3,3,3]
        else false
      end
    end

    def random_grid_row
      @layout_column_counts.sample
    end

    def remaining_collection_items
      @pristine_collection.count - @rows.flatten.count
    end
  end
end

app/views/admin/studies/_form.html.haml
= form_for @study, url:admin_study_path(@study), :html => { :class => 'form-horizontal', multipart:true } do |f|
  .control-group
    = f.label :slug, :class => 'control-label'
    .controls
      = f.text_field :slug, :class => 'text_field'
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :ref_link, :class => 'control-label'
    .controls
      = f.text_field :ref_link, :class => 'text_field'
  .control-group
    = f.label :poster_img, :class => 'control-label'
    .controls
      = f.file_field :poster_img, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      admin_studies_path, :class => 'btn'                          |

app/views/admin/studies/edit.html.haml
- model_class = Study
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

app/views/admin/studies/index.html.haml
- model_class = Study
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize
  -# %ul.thumbnails
  -#   %li.thumbnail
  -#     %article
  -#       %h3 study.title
  -#       %dl.dl-horizontal

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:slug)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:ref_link)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @studies.each do |study|
      %tr.study
        %td= link_to study.id, admin_studies_path(study)
        %td= study.slug
        %td= study.title
        %td= study.description
        %td= study.ref_link
        %td= l study.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), |
            edit_admin_study_path(study), :class => 'btn btn-mini'   |
          -#
          = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
            admin_study_path(study),                                                                                     |
            :method => :delete,                                                                                          |
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
            :class => 'btn btn-mini btn-danger'                                                                          |
= link_to t('.new', :default => t("helpers.links.new")), new_admin_study_path, :class => 'btn btn-primary'

app/views/admin/studies/new.html.haml
- model_class = Study
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

app/views/admin/studies/show.html.haml
- model_class = Study
.page-header
  %h1= t '.title', :default => model_class.model_name.human
%dl#study.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:slug)
      \:
  %dd= @study.slug
  %dt
    %strong
      = model_class.human_attribute_name(:title)
      \:
  %dd= @study.title
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= @study.description
  %dt
    %strong
      = model_class.human_attribute_name(:ref_link)
      \:
  %dd= @study.ref_link
  %dt
    %strong
      = model_class.human_attribute_name(:poster_img)
      \:
  %dd= @study.poster_img.url
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    admin_studies_path, :class => 'btn'                      |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_admin_study_path(@study), :class => 'btn'           |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    admin_study_path(@study),                                                                                    |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |